import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import Navbar from "@/components/Navbar/navbar-component";
import MobileSidebar from "@/components/shared/sidebar/mobile-sidebar";
import TeacherModal from "@/components/shared/models/teacher-modal";
import "@/style/globals.css";
import { getRequest } from "@/actions/getRequests";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const teacherRequest = await getRequest();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <MobileSidebar />
          <Toaster />
          <TeacherModal request={teacherRequest} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
